apiVersion : v1
kind : Pod
metadata:
  name: nginx-pod

spec:
  containers:
    - name : nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "100m"
          memory: "128mi"
